### PR TITLE
App: Added mocha opts

### PR DESCRIPTION
**Pull request by techmsi**
https://trello.com/c/cZAohbPf/9-add-tests-to-clay

### CODE REVIEW

**Comment by techmsi** [comment]
In a previous pull request, I included `mocha` devDep the `package.json` template.

**Comment by yoshokatana** [comment]
This won't actually move `test/mocha.opts` into the generated instance...would it?

**Comment by techmsi** [comment]
@yoshokatana No. That is the next piece.

**Comment by yoshokatana** [comment]
Oh. Why don't you do that in this PR?

**Comment by techmsi** [comment]
Added that to this PR.

**Comment by yoshokatana** [comment]
:+1:

**Pull request merged**
